### ISSUE TITLE
:reg causes loss of focus of cursor

### ISSUE THREAD

**Issue by sourcevault** [gerardroche/dotfiles#1]
On this vim command:

https://github.com/gerardroche/dotfiles/blob/969e1f580701bd5900614ee6aaf8d7b900890599/src/.vimrc#L418C1-L418C27

wouldnt something like this be better :

```.vimrc
noremap <leader>r :reg<bar>:FocusGroup group=0<CR>
```

as `:reg` causes the cursor to lose focus.

what are the drawbacks ?

**Comment by gerardroche** [comment]
You can press enter to close  the reg window. I tend to not want the reg window to stay open. I usually just want to peek at it. In the cases where I want to leave it open I'll use  `ctrl+1` to put the focus back on the view.
